### PR TITLE
trying to fix dir traversal <3

### PR DESCRIPTION
**Pull request by B3EF**
in the index.js path template paths are the only thing i think they are validating there,so it will be the place when a new url in given as in put is used to trigger path traversal.

### CODE REVIEW

**Review by toufik-airane — CHANGES_REQUESTED** [review]
The pull request doesn't meet the quality requirement. 🚫

**The contribution doesn't pass the unit test.**
```
🔥  larvitbase-www [7ed042a] ⚡  yarn test
yarn run v1.22.0
$ ./node_modules/tape/bin/tape ./test/*
/Users/toufikairane/Desktop/larvitbase-www/index.js:179
const filePathAbsolute = path.join(path1, path2Clean);
      ^

SyntaxError: Identifier 'filePathAbsolute' has already been declared
    at wrapSafe (internal/modules/cjs/loader.js:1067:16)
    at Module._compile (internal/modules/cjs/loader.js:1115:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/toufikairane/Desktop/larvitbase-www/test/01basics.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Review by JamieSlome — COMMENTED** [review]
Thank you for your submission! Please feel free to re-attempt your pull request for review next week.

**Comment by B3EF** [comment]
sir , 
i don't think there is a fix needed for this module ,as this module is working under the support of different laravite node modules , the entire laravite project is having a module named laravite router which is responsible for restricting the directory traversal in the entire laravite program that we are setting it up from the README file in the laravitebase-www module, so i think the problem is already fixed using the laravite router module
if you think i having a wrong concept please don't hesitate to inform me 
any way i was not able to recreate Directory traversal from my setup due to the protection provided by laravite router
thanks

**Comment by JamieSlome** [comment]
> sir ,
> i don't think there is a fix needed for this module ,as this module is working under the support of different laravite node modules , the entire laravite project is having a module named laravite router which is responsible for restricting the directory traversal in the entire laravite program that we are setting it up from the README file in the laravitebase-www module, so i think the problem is already fixed using the laravite router module
> if you think i having a wrong concept please don't hesitate to inform me
> any way i was not able to recreate Directory traversal from my setup due to the protection provided by laravite router
> thanks

@toufik-airane - thoughts?

**Comment by toufik-airane** [comment]
@x0xBEeF thank you for the deep investigation and analysis.
Indeed **larvitbase** uses **larvitrouter** to handle access to a resource and mitigate directory traversal.

However, the use of **larvitbase-www** without appropriate routing leads to exposing the app to the security issue we are trying to fix.

I think we should pursue our goal to develop a security fix with particular attention to not introduce an incompatibility with the use of larvitrouter. For the purpose and to gain confidence, we have to:
- pass unit test on larvitbase-www
- pass integration test on larvitbase (if it exists)

@JamieSlome What do you think about it?
Thanks for your attention.

_Reference_
[larvitbase](https://github.com/larvit/larvitbase)
[larvitbase-www](https://github.com/larvit/larvitbase-www)

**Comment by JamieSlome** [comment]
I agree with the comments provided by @toufik-airane! Please attempt to resolve this issue against the unit test on ```larvitbase-www``` & the integration test against ```larvitbase``` - thanks 🍰!

**Comment by B3EF** [comment]
Ok i get it... Thanks for the info

**Pull request closed without merging**
